{
  "uid" : "308c4a37fe2bc14e",
  "name" : "An uncaught error was detected outside of a test",
  "fullName" : "An uncaught error was detected outside of a test",
  "historyId" : "c59643030e1e776644fd5d1d6aa79cfc",
  "time" : {
    "start" : 1626648857041,
    "stop" : 1626648857048,
    "duration" : 7
  },
  "status" : "failed",
  "statusMessage" : "The following error originated from your test code, not from Cypress.\n\n  > Suite \"All elements on the planets page displayed On /new? \" was defined but no callback was supplied. Supply a callback or explicitly skip the suite.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
  "statusTrace" : "TypeError: The following error originated from your test code, not from Cypress.\n\n  > Suite \"All elements on the planets page displayed On /new? \" was defined but no callback was supplied. Supply a callback or explicitly skip the suite.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at createInvalidArgumentTypeError (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:102924:13)\n    at createMissingArgumentError (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:102911:10)\n    at Object.create (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:103306:17)\n    at context.describe.context.context (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:103079:27)\n    at https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:155952:21\n    at Object.create (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:103303:19)\n    at context.describe.context.context (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:103079:27)\n    at https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:155952:21\n    at https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:158509:16\n    at arrayEach (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:26494:11)\n    at Function.forEach (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:35374:14)\n    at evalScripts (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:158508:5)\n    at https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:158516:113\nFrom previous event:\n    at runScriptsFromUrls (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:158516:97)\n    at Object.runScripts (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:158530:10)\n    at $Cypress.onSpecWindow (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:147958:18)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "time" : { },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "The following error originated from your test code, not from Cypress.\n\n  > Suite \"All elements on the planets page displayed On /new? \" was defined but no callback was supplied. Supply a callback or explicitly skip the suite.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
    "statusTrace" : "TypeError: The following error originated from your test code, not from Cypress.\n\n  > Suite \"All elements on the planets page displayed On /new? \" was defined but no callback was supplied. Supply a callback or explicitly skip the suite.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at createInvalidArgumentTypeError (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:102924:13)\n    at createMissingArgumentError (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:102911:10)\n    at Object.create (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:103306:17)\n    at context.describe.context.context (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:103079:27)\n    at https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:155952:21\n    at Object.create (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:103303:19)\n    at context.describe.context.context (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:103079:27)\n    at https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:155952:21\n    at https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:158509:16\n    at arrayEach (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:26494:11)\n    at Function.forEach (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:35374:14)\n    at evalScripts (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:158508:5)\n    at https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:158516:113\nFrom previous event:\n    at runScriptsFromUrls (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:158516:97)\n    at Object.runScripts (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:158530:10)\n    at $Cypress.onSpecWindow (https://npplanets.herokuapp.com/__cypress/runner/cypress_runner.js:147958:18)",
    "steps" : [ ],
    "attachments" : [ {
      "name" : "planets.page.test.js.mp4",
      "type" : "video/mp4",
      "size" : 0
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "time" : { },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "975171ae9906bf6e",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Suite \"All elements on the planets page displayed \" was defined but no callback was supplied. Supply a callback or explicitly skip the suite.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626648825993,
        "stop" : 1626648826008,
        "duration" : 15
      }
    }, {
      "uid" : "e0086de52a4816a0",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > randomString is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626648218578,
        "stop" : 1626648218590,
        "duration" : 12
      }
    }, {
      "uid" : "6979fd53c7e48621",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > randomString is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626648144800,
        "stop" : 1626648144908,
        "duration" : 108
      }
    }, {
      "uid" : "de8784c90142f74e",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Suite \"All elements on the planets page displayed Pagination items works correctly Button \"Create\" on \" was defined but no callback was supplied. Supply a callback or explicitly skip the suite.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626644255597,
        "stop" : 1626644255652,
        "duration" : 55
      }
    }, {
      "uid" : "df8d31f3fa75f489",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Test argument \"title\" should be a string. Received type \"undefined\"\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626617297383,
        "stop" : 1626617297414,
        "duration" : 31
      }
    }, {
      "uid" : "eded98f549c2eb49",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Test argument \"title\" should be a string. Received type \"undefined\"\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626559036884,
        "stop" : 1626559036894,
        "duration" : 10
      }
    }, {
      "uid" : "abe28f7c283e7025",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Cannot read property 'userName1' of undefined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626534881796,
        "stop" : 1626534881814,
        "duration" : 18
      }
    }, {
      "uid" : "b92455d9cf14122",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Class extends value undefined is not a constructor or null\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626527648308,
        "stop" : 1626527648337,
        "duration" : 29
      }
    }, {
      "uid" : "f2267ec5acd24df5",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Class extends value undefined is not a constructor or null\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626527621603,
        "stop" : 1626527621753,
        "duration" : 150
      }
    }, {
      "uid" : "b49c2fcef6306d63",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Class extends value undefined is not a constructor or null\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626527583426,
        "stop" : 1626527583450,
        "duration" : 24
      }
    }, {
      "uid" : "5e344db524ccf50c",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Class extends value #<ElementsOnAllPages> is not a constructor or null\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626527362023,
        "stop" : 1626527362043,
        "duration" : 20
      }
    }, {
      "uid" : "d66924572d85018d",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Class extends value #<ElementsOnAllPages> is not a constructor or null\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626527337715,
        "stop" : 1626527337745,
        "duration" : 30
      }
    }, {
      "uid" : "1733018a843ed748",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Class extends value undefined is not a constructor or null\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626527306325,
        "stop" : 1626527306377,
        "duration" : 52
      }
    }, {
      "uid" : "1048ad319be75e31",
      "status" : "failed",
      "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Class extends value undefined is not a constructor or null\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
      "time" : {
        "start" : 1626527260197,
        "stop" : 1626527260239,
        "duration" : 42
      }
    } ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "308c4a37fe2bc14e.json",
  "parameterValues" : [ ]
}